from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path


REQUIRED_TIMING_LABELS = (
    "main_sense_pulse_end",
    "alt_sense_pulse_start",
    "alt_sense_pulse_end",
    "actuation_pulse_start",
)


def iso_timestamps_pair(now: datetime | None = None) -> tuple[str, str]:
    current = now or datetime.now().astimezone()
    utc_ts = current.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
    local_ts = current.isoformat()
    return utc_ts, local_ts


def relative_path(path: Path, experiment_dir: Path) -> str:
    try:
        return str(path.resolve().relative_to(experiment_dir.resolve()))
    except Exception:
        return str(path)


def default_assignment_entries() -> dict[str, str]:
    entries: dict[str, str] = {}
    for i in range(16):
        entries[f"button_{i}"] = "N/A"
    for i in range(16):
        entries[f"slider_{i}"] = "N/A"
    for i in range(2):
        entries[f"pedal_{i}"] = "N/A"
    return entries


def normalise_controls(arm_snapshot: dict | None) -> dict:
    raw_buttons = [False] * 16
    raw_sliders = [0.0] * 16
    raw_pedals = [0.0] * 2
    assignment_entries = default_assignment_entries()
    interpreted_state = {}
    assignment_source = "manual"
    assignment_version = "unknown"

    if isinstance(arm_snapshot, dict):
        controls = arm_snapshot.get("controls")
        if isinstance(controls, dict):
            raw_state = controls.get("raw_state")
            if isinstance(raw_state, dict):
                buttons = raw_state.get("buttons")
                if isinstance(buttons, list):
                    raw_buttons = [bool(v) for v in buttons[:16]] + [False] * max(0, 16 - len(buttons))
                sliders = raw_state.get("sliders")
                if isinstance(sliders, list):
                    raw_sliders = [float(v) for v in sliders[:16]] + [0.0] * max(0, 16 - len(sliders))
                pedals = raw_state.get("pedals")
                if isinstance(pedals, list):
                    raw_pedals = [float(v) for v in pedals[:2]] + [0.0] * max(0, 2 - len(pedals))

            assignment_map = controls.get("assignment_map")
            if isinstance(assignment_map, dict):
                assignment_source = str(assignment_map.get("source", "manual"))
                assignment_version = str(assignment_map.get("version_tag", "unknown"))
                entries = assignment_map.get("entries")
                if isinstance(entries, dict):
                    for key, value in entries.items():
                        assignment_entries[str(key)] = str(value)

            parsed_interpreted = controls.get("interpreted_state")
            if isinstance(parsed_interpreted, dict):
                interpreted_state = parsed_interpreted

    return {
        "raw_state": {
            "buttons": raw_buttons,
            "sliders": raw_sliders,
            "pedals": raw_pedals,
        },
        "interpreted_state": interpreted_state,
        "assignment_map": {
            "source": assignment_source,
            "version_tag": assignment_version,
            "entries": assignment_entries,
        },
    }


def fallback_flexpwm_timing(sample_rate_hz: int) -> dict:
    period_us = (1000000.0 / float(sample_rate_hz)) if sample_rate_hz > 0 else 0.0
    rows = [
        {
            "label": label,
            "cycle_value": 0,
            "duty_cycle": 0.0,
            "time_us": 0.0,
        }
        for label in REQUIRED_TIMING_LABELS
    ]
    return {
        "reference": {
            "time_zero_symbol": "FLEXPWM2_SM0VAL0",
            "time_zero_cycle": 0,
        },
        "config_constants": {
            "samplerate_hz": sample_rate_hz,
            "max_duty_ch1": 0.0,
            "max_duty_ch2": 0.0,
            "resolution_pwm_bits": 0,
        },
        "derived": {
            "cycles": 0,
            "val_input": 0,
            "period_us": period_us,
            "period_cycles": 1,
            "cycles_formula": "cycles = (val * period_cycles) >> resolution_pwm_bits",
        },
        "consistency_checks": {
            "all_actuation_start_times_equal": False,
            "note": "Fallback metadata generated by Python due to missing firmware telemetry.",
        },
        "timing_table": rows,
    }


def normalise_flexpwm_timing(arm_snapshot: dict | None, sample_rate_hz: int) -> dict:
    if not isinstance(arm_snapshot, dict):
        return fallback_flexpwm_timing(sample_rate_hz)
    timing = arm_snapshot.get("flexpwm_tdm_timing")
    if not isinstance(timing, dict):
        return fallback_flexpwm_timing(sample_rate_hz)

    table = timing.get("timing_table")
    if not isinstance(table, list):
        table = []
    labels = {str(row.get("label")) for row in table if isinstance(row, dict)}
    for label in REQUIRED_TIMING_LABELS:
        if label not in labels:
            table.append(
                {
                    "label": label,
                    "cycle_value": 0,
                    "duty_cycle": 0.0,
                    "time_us": 0.0,
                }
            )
    timing["timing_table"] = table
    return timing


def infer_trial_status(streams: dict) -> str:
    for stream in streams.values():
        if not isinstance(stream, dict):
            continue
        if stream.get("requested") and stream.get("status") == "failed":
            return "failed"
    return "success"
